name: Raksha
description: "A Flutter-based emergency ambulance alert system that provides real-time emergency services to users and ambulance drivers."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  file_picker: ^8.0.0
  google_maps_flutter: ^2.5.0
  location: ^6.0.0
  permission_handler: ^12.0.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png.png"  # Path to your icon (1024x1024)
  min_sdk_android: 21
  dependencies:
  http: ^1.1.0
